version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - DB_USER=postgres
      - DB_PASSWORD=your_password
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=leaderboard
      - GAME_NAMES=game_1,game_2,game_3,game_4,game_5
      - GAME_DISPLAY_NAMES=遊戲一,遊戲二,遊戲三,遊戲四,遊戲五

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - .postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    links:
      - backend
